from calendar import c
import os
import requests as req
import curses
from subprocess import STDOUT, Popen
from curses import wrapper
from curses.textpad import Textbox, rectangle

def getLatestBuild(project, version):
    url = f"https://papermc.io/api/v2/projects/{project}/versions/{version}"
    resp = req.get(url)
    data = resp.json()
    return max(data["builds"])

def getDownloadURL(project, version, build):
    return f"https://papermc.io/api/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{project}-{version}-{build}.jar"

def downloadFile(stdscr, file):
    if file == 'BungeeCord':
        stdscr.clear()
        stdscr.addstr("Downloading 'BungeeCord.jar'")
        stdscr.refresh()
        proc = Popen('wget https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar', shell=True, stdin=None, stdout=open(os.devnull,"wb"), stderr=STDOUT, executable="/bin/bash")
        proc.wait()
        stdscr.clear()
        stdscr.addstr("Download completed for 'BungeeCord.jar'")
        stdscr.refresh()
    elif file == 'Velocity':
        stdscr.clear()
        stdscr.addstr("Downloading 'Velocity'")
        stdscr.addstr("\n" + f'wget -O Velocity.jar {getDownloadURL("velocity", "3.1.1", getLatestBuild("velocity", "3.1.1"))}')
        stdscr.refresh()
        proc = Popen(f'wget {getDownloadURL("velocity", "3.1.1", getLatestBuild("velocity", "3.1.1"))}', shell=True, stdin=None, stdout=open(os.devnull,"wb"), stderr=STDOUT, executable="/bin/bash")
        proc.wait()
        stdscr.clear()
        stdscr.addstr("Download completed for 'Velocity.jar'")
        stdscr.refresh()
    elif file == 'Craftbukkit':
        return ''
def splashScreen(stdscr):
    stdscr.clear()
    stdscr.addstr("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("#(((((((((((&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("                              TheDeQ Minecraft Server Toolkit V.1", curses.color_pair(3))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("####(########(", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("          This program will convert the current directory to a Minecraft Server or Proxy.", curses.color_pair(3))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("#####", curses.color_pair(2))
    stdscr.addstr("@@@@&", curses.color_pair(1))
    stdscr.addstr("####(", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("          This program were created for use by TheDeQ Developers to easier setup servers.", curses.color_pair(3))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("#####", curses.color_pair(2))
    stdscr.addstr("@@@@&", curses.color_pair(1))
    stdscr.addstr("####(", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("%%%%%%", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("          This script currently (10/2-2022) only works on linux tested on Ubuntu 20.04.", curses.color_pair(3))
    stdscr.addstr("\n@@@@@@", curses.color_pair(1))
    stdscr.addstr("&&%%%%%%%%%@#####", curses.color_pair(2))
    stdscr.addstr("@@@&&", curses.color_pair(1))
    stdscr.addstr("####(", curses.color_pair(2))
    stdscr.addstr("@@@", curses.color_pair(1))
    stdscr.addstr("&&%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@&", curses.color_pair(1))
    stdscr.addstr("%%%%&", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("####(#####(##(", curses.color_pair(2))
    stdscr.addstr("@@@@@", curses.color_pair(1))
    stdscr.addstr("&%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@&", curses.color_pair(1))
    stdscr.addstr("%%%%&", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("###########", curses.color_pair(2))
    stdscr.addstr("@@@@@@@", curses.color_pair(1))
    stdscr.addstr("&%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@&", curses.color_pair(1))
    stdscr.addstr("%%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("&%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@", curses.color_pair(1))
    stdscr.addstr("&%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@&", curses.color_pair(1))
    stdscr.addstr("%%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("%%%%%%%%%%%%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@&", curses.color_pair(1))
    stdscr.addstr("%%%%&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("&&&%%%%&&&&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("%%%%%&&&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("%%%%", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("#####%", curses.color_pair(2))
    stdscr.addstr("@@@@@", curses.color_pair(1))
    stdscr.addstr("#####", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("%", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("&", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("##", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("#%&#", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("#", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("#%", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("%#", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("&", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("&&", curses.color_pair(2))
    stdscr.addstr("@", curses.color_pair(1))
    stdscr.addstr("%%%%%", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("&%%", curses.color_pair(2))
    stdscr.addstr("@@", curses.color_pair(1))
    stdscr.addstr("%#%", curses.color_pair(2))
    stdscr.addstr("@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@", curses.color_pair(1))
    stdscr.addstr("          Press ENTER key to contine!", curses.color_pair(1))
    stdscr.refresh()
    key = stdscr.getch()
    if key == curses.KEY_ENTER or key == 10 or key == 13:
        menu(stdscr)

def menu(stdscr):
    stdscr.clear()
    stdscr.refresh()
    stdscr.addstr("Minecraft Server Toolkit", curses.color_pair(3))
    stdscr.addstr("\nWhat software do you want to install?", curses.color_pair(1))
    stdscr.addstr("\n[6] BungeeCord", curses.color_pair(1))
    stdscr.addstr("\n[5] Velocity", curses.color_pair(1))
    stdscr.addstr("\n[4] Craftbukkit", curses.color_pair(1))
    stdscr.addstr("\n[3] Spigot", curses.color_pair(1))
    stdscr.addstr("\n[2] Paper", curses.color_pair(1))
    stdscr.addstr("\n[1] Purpur", curses.color_pair(1))
    stdscr.addstr("\n$ ", curses.color_pair(1))
    stdscr.refresh()
    key = stdscr.getch()
    if key == 54:
        downloadFile(stdscr, 'BungeeCord')
    elif key == 53:
        downloadFile(stdscr, 'Velocity')
    elif key == 52:
        downloadFile(stdscr, 'Craftbukkit')
    elif key == 51:
        downloadFile(stdscr, 'Spigot')
    elif key == 50:
        downloadFile(stdscr, 'Paper')
    elif key == 49:
        downloadFile(stdscr, 'Purpur')
    else:
        menu()
        
def main(stdscr):
    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_GREEN, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_CYAN, curses.COLOR_BLACK)
    curses.init_pair(4, curses.COLOR_WHITE, curses.COLOR_BLACK)
    splashScreen(stdscr)
    

wrapper(main)



